worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        location /hls {
            root /app;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /playlist.m3u {
            root /app;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
