worker_processes auto;
events {}

http {
    sendfile on;

    server {
        listen 80;

        location / {
            root /app/streams;
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }
    }
}
